CREATE TABLE counters
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    sector_id   INT         NOT NULL,
    name        VARCHAR(50) NOT NULL,
    description TEXT,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sector_id) REFERENCES sectors (id) ON DELETE CASCADE
);